# Generated by Django 4.0.6 on 2022-08-10 14:35

from django.db import migrations, models
import wsgiref.handlers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('estatura', models.FloatField()),
                ('fecha_nacimiento', models.DateField(verbose_name=wsgiref.handlers.format_date_time)),
            ],
        ),
    ]
